Upd. Processing the get parameter
CleanTalk/php-usp pull request #26
Opened 2024-05-02 18:28 UTC by AntonV1211

https://doboard.com/task/7454

2024-05-03 12:39 UTC, alexandergull requested changes

2024-05-03 12:39 UTC, alexandergull commented on uniforce/router.php
> +    case \Cleantalk\USP\Variables\Cookie::get('authentificated') === \Cleantalk\USP\Common\State::getInstance()->data->security_key || $first_load === 1:
If first_load param is not 0 or 1, the $page variable is undefined.

2024-05-06 06:43 UTC, Glomberg approved these changes

2024-05-06 10:18 UTC, alexandergull approved these changes

2024-05-08 06:36 UTC, merged